import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Sidebar } from '@/components/sidebar';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ZuAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='bg-[#e5ecf3]'>
      <body className={inter.className}>
        <Sidebar />
        <main className='bg-[#e5ecf3]'>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}