import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Sidebar } from '@/components/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ZuAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' 
    className='bg-[#e5ecf3]'
    >
      <body className={inter.className}>
          <Sidebar />
        <main 
        // className='mx-5 mt-16 sm:ml-[100px] sm:mt-3'
        >{children}</main>
      </body>
    </html>
  );
}